### PR TITLE
fix(test): #321 Correct promises error handling

### PR DESCRIPTION
**Pull request by deeptibaghel**
Fixed and tested all problematic promised error handling calls. One modified non-existing api call was getting caught at incorrect place due to the issue. Fixed the api call at two places.

### CODE REVIEW

**Comment by deeptibaghel** [comment]
@eoger  918 - 971 - 1014 - 1177 - 1347 is done.
could you pl. mark this block : "1363-1379 (can be in a top level then())"

**Comment by eoger** [comment]
Thanks!
> could you pl. mark this block : "1363-1379 (can be in a top level then())"

[This block](https://github.com/deeptibaghel/fxa-auth-db-mysql/blob/af14c29ccd7a245d76d98c2a6ce146dbd185a6b4/db-server/test/backend/remote.js#L1373-L1375) could be a top-level block. Same for [this one](https://github.com/deeptibaghel/fxa-auth-db-mysql/blob/af14c29ccd7a245d76d98c2a6ce146dbd185a6b4/db-server/test/backend/remote.js#L1389-L1391).

**Comment by deeptibaghel** [comment]
Thanks a lot @eoger :)

**Pull request merged**
