### PR TITLE
refactor(config): Use human-readable duration values in config

### PR DESCRIPTION
**Pull request by pdehaan**
Ref: https://github.com/mozilla/fxa-oauth-server/issues/296

### CODE REVIEW

**Comment by chilts** [comment]
Does this need a corresponding change for `pruneEvery` in fxa-dev? Looks fine to me, r+, so long a @jrgm is happy ... since he'll be doing the changes to prod.

**Comment by pdehaan** [comment]
IIUC, for a `format: 'duration',` it allows you to specify milliseconds or a `moment` parseable string. Not sure if we need to change other configs downstream or if the existing behavior will still apply to fxa-dev/prod.

> `duration` - milliseconds or a human readable string (e.g. 3000, "5 days")
> &mdash; via https://github.com/mozilla/node-convict#validation

**Comment by chilts** [comment]
Ah right, cool. Thanks @pdehaan.

**Pull request merged**
