### PR TITLE
Train 89 uplift

### PR DESCRIPTION
**Pull request by vbudhram**
Trains 89.1 and 89.3 contained updates to the `accountEmails` and `forgotPasswordVerified`. This PR uplifts those changes and increments all the preceding migrations.

### CODE REVIEW

**Comment by vbudhram** [comment]
@mozilla/fxa-devs Mind an r? This is needed before tagging train 90.

**Comment by philbooth** [comment]
Fwiw, I reckon we should squash those `chore` commits so that we don't leave broken commits in the tree.

**Comment by philbooth** [comment]
@vbudhram, I still see the effects of mozilla/fxa-auth-server#1963 when I run the auth server tests from `master` against this branch of the mysql db. Can we eliminate the flakiness? (or am I doing something wrong?)

**Comment by philbooth** [comment]
> I still see the effects of mozilla/fxa-auth-server#1963...

This was untrue.

**Comment by philbooth** [comment]
This looks good to me!

**Pull request merged**
