### PR TITLE
chore(package.json): add extra fields related to the repo

### PR DESCRIPTION
**Pull request by chilts**
Things like homepage, bugs and keywords.

### CODE REVIEW

**Comment by chilts** [comment]
@pdehaan r?

**Comment by chilts** [comment]
Hmm.

**Comment by chilts** [comment]
Yeah, it was just Travis the first time. Looks ok.

**Comment by pdehaan** [comment]
Re: "repository": "mozilla/fxa-auth-db-mysql",

Not sure if we want to use the long-form for that.
```js
  "repository": {
    "type": "git",
    "url": "https://github.com/mozilla/fxa-auth-db-mysql"
  },
```

I think @jrgm was seeing some issues with running **grunt-conventional-changelog** against repos with the short-notation (digs up bug number &mdash; https://github.com/mozilla/fxa-profile-server/pull/100). Probably not a big deal; especially if we aren't planning on using Grunt to generate changelogs in this repo -- plus, this should be fixed in latest **conventional-changelog** and **grunt-conventional-changelog**'s master branch (but not in latest published npm version yet).

**Comment by pdehaan** [comment]
Apart from the one nit, :+1: from me, merge when ready.

**Comment by pdehaan** [comment]
```
$ node cli -r mozilla/fxa-auth-db-mysql -o console
mozilla/fxa-auth-db-mysql

package.json
info:
- info: package.json is almost fine. Check the file and run again.
warning:
- warning: missing 'bugs'
- warning: missing 'keywords'
- warning: missing 'homepage'


package.json outdated:
DEPENDENCIES:
NAME                REQUIRED                                                  STABLE  LATEST
bluebird            2.1.3                                                     2.9.14  2.9.14
clone               0.2.0                                                     1.0.1   1.0.1
convict             0.4.2                                                     0.6.1   0.6.1
fxa-auth-db-server  git://github.com/mozilla/fxa-auth-db-server.git#train-33
fxa-jwtool          0.4.0                                                     0.6.0   0.6.0
mysql               2.3.2                                                     2.5.5   2.5.5
request             2.53.0                                                    2.54.0  2.54.0

DEVDEPENDENCIES:
NAME                  REQUIRED                               STABLE  LATEST
ass                   git://github.com/jrgm/ass.git#5be99ee
grunt-contrib-jshint  0.10.0                                 0.11.1  0.11.1
load-grunt-tasks      0.6.0                                  3.1.0   3.1.0
mysql-patcher         0.5.1                                  0.7.0   0.7.0
nock                  1.2.0                                  1.2.1   1.2.1
restify               2.8.1                                  3.0.1   3.0.1
tap                   0.4.13                                 0.7.1   0.7.1
uuid                  1.4.1                                  2.0.1   2.0.1

shrinkwrap.json:
MODULE     VERSION  TITLE                                                 PATCHED   DEPENDENCY
validator  1.5.1    validator isURL Regular Expression Denial of Service  >=3.22.1  fxa-auth-db-mysql > convict
validator  1.5.1    Validator XSS Filter Bypass via Encoded URL           >=2.0.0   fxa-auth-db-mysql > convict
qs         0.6.6    qs Denial-of-Service Extended Event Loop Blocking     >= 1.x    fxa-auth-db-mysql > restify
qs         0.6.6    qs Denial-of-Service Memory Exhaustion                >= 1.x    fxa-auth-db-mysql > restify
```

**Pull request merged**
