### PR TITLE
fix(notifications): always return a promise from db.processUnpublishedEvents, fixes #49

### LINKED ISSUE #49: lib/db/mysql.js - unhandled TypeError when running on an fxa-dev box
Noticed that the auth-db-mysql server on an fxa-dev is filling its logs with the exception below. 

I believe that this is due to the change from p-promise to bluebird, and that [this function](https://github.com/mozilla/fxa-auth-db-mysql/blob/master/bin/server.js#L51-L58) should ensure that it always returns a promise on any path (events or no events), (`P.resolve()`?).

```
Possibly unhandled TypeError: Cannot call method 'then' of undefined
    at query.then.then.log.error.op (/data/fxa-auth-db-mysql/lib/db/mysql.js:734:20)
    at tryCatch1 (/data/fxa-auth-db-mysql/node_modules/bluebird/js/main/util.js:43:21)
    at Promise$_callHandler [as _callHandler] (/data/fxa-auth-db-mysql/node_modules/bluebird/js/main/promise.js:627:13)
    at Promise$_settlePromiseFromHandler [as _settlePromiseFromHandler] (/data/fxa-auth-db-mysql/node_modules/bluebird/js/main/promise.js:641:18)
    at Promise$_settlePromiseAt [as _settlePromiseAt] (/data/fxa-auth-db-mysql/node_modules/bluebird/js/main/promise.js:800:14)
    at Promise$_settlePromises [as _settlePromises] (/data/fxa-auth-db-mysql/node_modules/bluebird/js/main/promise.js:934:14)
    at Promise.b (domain.js:183:18)
    at Async$_consumeFunctionBuffer [as _consumeFunctionBuffer] (/data/fxa-auth-db-mysql/node_modules/bluebird/js/main/async.js:75:12)
    at Async$consumeFunctionBuffer (/data/fxa-auth-db-mysql/node_modules/bluebird/js/main/async.js:38:14)
    at process._tickDomainCallback (node.js:492:13)
```

### PR DESCRIPTION
**Pull request by jrgm**
r? anyone. Is this the best way to do this. Not needed for production, but would be nice to remove this spew in fxa-dev log asap.

### CODE REVIEW

**Comment by rfk** [comment]
Thanks @jrgm.  Looking into it briefly, I think we're better off promisifying this inside `db.processUnpublishedEvents` so that any future callers of that function don't hit the same issue.  

IIUC it needs to guard against the passed callback not returning a promise, so this:
```
return fn(events).then(...)
```

Should be more like:
```
return P.resolve(events).then(fn).then(...)
```

**Comment by jrgm** [comment]
@rfk - Thanks. I switched to fixing within `db.processUnpublishedEvents` as you suggested, and adding a test that would fail on `master`.

**Comment by jrgm** [comment]
Let's not land this in train-39, but let's definitely get this in after master is branched because this is filling the logs on fxa-dev instances with noise.

**Comment by rfk** [comment]
whoops, forgot to r? this yesterday....r+ :-)

**Comment by jrgm** [comment]
So, train-39 was branch Wednesday. Merging this to master now and will check that chirping on fxa-dev is gone in a bit.

**Comment by jrgm** [comment]
Logs on fxa-dev no longer chirping with noise.

**Pull request merged**
