### PR TITLE
refactor(lib): move most things into lib/

### PR DESCRIPTION
**Pull request by chilts**
All top level *.js files have been moved into lib/. However everything
in bin/ and config/ has been left where it is. Only two minor fixes for
the path to test/local/test-secret.pem were also made.

### CODE REVIEW

**Comment by pdehaan** [comment]
@chilts Cool story, bro.
Do you need to update any Grunt tasks to also point to the new ./lib/** folder?

**Comment by chilts** [comment]
@pdehaan yes. Thanks. :)

**Comment by chilts** [comment]
Hmm, I've (force) re-pushed but Travis isn't rebuilding the PR. Not sure why. Only change in this last commit was the two Grunt tasks which reference `db/`, now `lib/`.

**Comment by dannycoates** [comment]
:+1: LGTM

**Comment by dannycoates** [comment]
@pdehaan you know what happened to that guy, right?

**Comment by pdehaan** [comment]
@dannycoates I do!

I'm... I'm sorry @chilts! #runsaway

**Comment by chilts** [comment]
:fried_shrimp: :8ball: :accept: :baby: :zap: :zap: :zap: :x: :ice_cream: :japanese_ogre: and :facepunch: for good measure!

**Pull request merged**
