### PR TITLE
feat(docker): add docker via Circle CI

### PR DESCRIPTION
**Pull request by vladikoff**
@jbuck could you please add the build creds to https://circleci.com/gh/mozilla/fxa-auth-db-mysql/edit#env-vars ?

### CODE REVIEW

**Comment by jbuck** [comment]
@vladikoff added creds, thanks for the reminder!

**Comment by seanmonstar** [comment]
Ah, just tried to push my own branch and enable circle, saw it was already enabled!

Only thing I see here is that since removing the old Dockerfile, the README instructions on using it are incorrect.

**Comment by vladikoff** [comment]
@jbuck so for tests to pass we will need a local `mysql` running I think. Should we use a docker container or something else?

**Comment by jbuck** [comment]
@vladikoff Circle says they have [MySQL running locally by default](https://circleci.com/docs/1.0/configuration/#services), so all you should need to do is add `--net="host"` to the docker run command so that the container can connect to it.

**Comment by vladikoff** [comment]
> @vladikoff Circle says they have MySQL running locally by default, so all you should need to do is add --net="host" to the docker run command so that the container can connect to it.

Sounds good! I'll just need to make sure it is MySql 5.6

**Pull request merged**
