### PR TITLE
chore(api): #318 remove bufferization from db layer

### PR DESCRIPTION
**Pull request by deeptibaghel**
Changes done :

1. Added new function in bufferize to utf8 encode the hex email parameter
2. Modified unit test for bufferize to handle new function
3. Removed utf8 conversion from both database files
4. Modified local db tests to pass unhexed email parameter

### CODE REVIEW

**Comment by deeptibaghel** [comment]
@vladikoff i am getting intermittent failures in one test 'email bounces' , how do I make debugger stop at  a particular test, i tried statement 'debugger' but it did not work.

**Comment by deeptibaghel** [comment]
@vladikoff so the failure was because email parameter is there in the form parameter of emailbounces post request, which was getting hex encoded unnecessarily. I have renamed the parameter email to emailHex, not sure if it is the right way. Now the tests are working.

**Comment by philbooth** [comment]
@deeptibaghel, although your `toUtfRequest` approach here works well, in this instance I think it's possibly a case of premature generalisation. It adds a fair amount of code/complexity for just one param name on four endpoints.

I think it might be better to keep things simple for now and just have a little helper function to wrap the `Buffer.from(value,'hex').toString('utf8')` part, then call that inline for each usage of `req.params.email` we need it on.

In the future, if we find ourselves needing to do it for other param names on other endpoints, then it might be the right time to introduce something like you've done here. But less code is better if possible!

**Comment by deeptibaghel** [comment]
@philbooth so convert it in index.js itself ?

**Comment by philbooth** [comment]
@deepti, hmm, it's okay keep it in `bufferize.js` I think, maybe just call it `hexToUtf8` or something. But doing it in `index.js` is also fine too as that's the only place it's used at the moment. Your call! 😄

**Comment by philbooth** [comment]
Perfect! Thanks @deeptibaghel!

**Pull request merged**
