### PR TITLE
feat(emails): Add account.email -> email table migration

### PR DESCRIPTION
**Pull request by vbudhram**
This is an PR adds the migration script to copy the account's email into the emails table. This will allow us simplify some of the SQL needed for changing a user's email. The commit of interest is https://github.com/mozilla/fxa-auth-db-mysql/commit/dc3ada6175b4274fcad5b106c9e9a03322508783, which just contains the migration.

@rfk @jbuck does this seem reasonable?

### CODE REVIEW

**Comment by rfk** [comment]
The approach looks reasonable to me.  @jbuck what do you think about the mechanics of doing this bulk copy-into-a-new-table in production?  Would we need to process the accounts in small batches to avoid tieing up the tables?

@vbudhram to ensure we're on the same page here, is the reason that it's done as a separate migration to allow us to roll it out safely, say in three phases like:

1) Add new stored procedures that treat `emails` table as canonical, but fall back to the main `accounts` table when it's missing.  Accounts created or modified after this point will have fully-populated `emails` table.
2) Copy over existing accounts into the `emails` table.  After this point the `emails` table is the full and complete source of truth, and nothing needs to do fallback lookups in the `accounts` table.
3) We can ship updated stored procedures that remove the fallback lookups in the main `accounts` table.  After this point, nothing touches the email-related columns in the `accounts` table.
4) We can actually drop the email-related columns from the `accounts` table.

Do I correctly understand where this is heading?

**Comment by rfk** [comment]
(That's a lot of deployments, and we could plan to do some of them off-train if we wanted to get through them all in a timely fashion).

**Comment by vbudhram** [comment]
> to ensure we're on the same page here

Yea, those are pretty much the steps I was thinking. However, I wasn't really thinking of dropping the `email` column on account table. Jon mentioned doing point releases for 1,2 and maybe 3 in another train.

**Comment by vbudhram** [comment]
Closing in favor of https://github.com/mozilla/fxa-auth-db-mysql/pull/247, which was branched from master.

**Pull request closed without merging**
