### PR TITLE
Train 122 lift 121

### PR DESCRIPTION
**Pull request by vbudhram**
This PR uplifts train-121 to train-122. It appends migration from https://github.com/mozilla/fxa-auth-db-mysql/pull/410 as migration 88.

### CODE REVIEW

**Comment by rfk** [comment]
>  After merging, train-122 migration 87 becomes migration 88.

Will this cause problems for dev environments that have already applied the previous migration 87?  I wonder if the migration that we're merging in should be the one that gets renumbered, rather than the one that's already on master.

**Comment by vbudhram** [comment]
@mozilla/fxa-devs r?

**Comment by vbudhram** [comment]
>  I wonder if the migration that we're merging in should be the one that gets renumbered, rather than the one that's already on master.

That would also work 👍🏽. The same thing would be needed for train-123, but it should make for a little easier merge.

**Comment by jrgm** [comment]
+1 on the issue for dev boxes that have already applied everything  that is on master. The new fix for the replication issue should become the next unused patch level.

I've built a checklist of recent changes that I'll double check with in stage and prod as I get those back in tune. Done in stage for fxa-auth now up to train-123.

**Comment by vbudhram** [comment]
@rfk @jrgm Thanks for recommendations, made updates, r?

**Pull request merged**
