### PR TITLE
feat(api): Return the account email address on passwordChangeToken

### LINKED ISSUE #58: PasswordChangeToken should support an email.
From https://github.com/mozilla/fxa-auth-server/pull/876/files#r32576784, this would enable the `/password/change/finish` endpoint to send a notification email with one fewer database hits.

### PR DESCRIPTION
**Pull request by chilts**
Fixes #58

### CODE REVIEW

**Comment by rfk** [comment]
Thanks @chilts!

I'm going to throw @philbooth into the deep end a little on this one and ask him for r?; this is a small change but it requires a lot of implied knowledge about wtf is going on in our db backend with stored procedurs etc, so a good chance for him to ask questions and point out things that aren't clear.

I assume this doesn't need to land with any particular urgency, so @philbooth feel free to take the time you need in amongst the other stuff you're working on.

**Comment by philbooth** [comment]
@chilts @rfk: I don't really have any questions tbh so perhaps it's better if I describe the changeset as I understand it, then one of you guys can point out anything I'm missing or have outright wrong. Sound reasonable?

So essentially we have a database migration with its associated rollback script, identified by the patch number `13`. Poking around in the repo it looks like the migrations are executed by `bin/db_patcher.js`, which itself relies on the npm module `mysql-patcher`.

The point of the change is to update `MySql.prototype.passwordChangeToken` so that it also selects the `email` field, which is not present in the previous version of the stored procedure.

Fwiw, this handily answers two questions I was wondering about after yesterday's domain model whiteboard session, namely:

1. Do we use an ORM? Answer: no.
2. Where are the db migrations? Answer: the directory `lib/db/schema` in this repo.

Does the above sound right-ish / am I missing anything?

**Comment by rfk** [comment]
Sounds right at a high level, @chilts may like to add more details.

> Do we use an ORM? Answer: no

Right, and TBH this is something that hasn't sat comfortably with me for a while.  When we started these codebases there was no obvious "right way" to abstract away db manipulations in nodejs, particularly not one with solid migration facilities.  We rolled our own thing rather than battle with immature tooling.  It's possible (likely?) the landscape has changed and we should revisit this decision at some point.

**Comment by chilts** [comment]
Hey @philbooth, that all sounds right to me. Yes, the migrations are in that directory in this repo but I suspect they are placed elsewhere in other repos e.g. https://github.com/mozilla/fxa-oauth-server/tree/master/lib/db/mysql/patches in the OAuth server.

One subtle thing you may or may not have noticed about the reverse patch is that all of the lines are actually commented out. This is essentially so that you can't somehow run the migration tool backwards and destroy things, it would have to be a very definite action to go into the file, uncomment everything and the re-run the patch. If the db_patcher was run in reverse, then the patch will fail since the db_patcher itself makes sure the `dbMetadata` row for `schema-patch-level` has actually been patched to the expected value and will quit if it hasn't (as added protection).

That's also not quite the whole truth, since the db_patcher is only used in dev (locally and in fxa-dev), but not used in production. That's done manually by the lovely @ckolos and the even lovelier @jrgm.

Who's r+'ing and merging me? (and yes, no rush)

**Comment by chilts** [comment]
@philbooth one more thing to note. In most patches, the reverse patch should (of course) do things in exactly the reverse order as the forward patch (mainly if there are any dependencies between each command). In this case there is only one SQL command so it doesn't matter. The update of the patch level of course comes at the end of each patch script.

Also, you'll notice that we created a v2 of a stored procedure here and dropped it in the reverse patch. I'm about to make a new issue so that v1 of that same stored procedure is dropped in the next release. So far we just did a big cleanup of the old stored procedures but from now we'll be tidying them up as we go, not because they use much space but they do give a surface area to the DB that we no longer need and perhaps could be either mis-used or abused.

**Comment by philbooth** [comment]
Thanks, that all makes sense. Well it's definitely r+ from me, not sure if I'm allowed to merge anything yet though @rfk?

**Comment by chilts** [comment]
@philbooth You can totally hit that green button!

**Comment by chilts** [comment]
Thanks @philbooth.

**Pull request merged**
