### PR TITLE
fix(server): fix bad route parameter name

### PR DESCRIPTION
**Pull request by philbooth**
Spotted this while testing out the device registration stuff, there's a mismatched parameter name on the `upsertDevice` route.

@dannycoates or @rfk, r?

### CODE REVIEW

**Comment by rfk** [comment]
Nice catch, thanks @philbooth.  I guess this also indicates a lack of test coverage on that endpoint which we should fix alongside it.

**Comment by philbooth** [comment]
Oh my bad, I totes forgot there are functional tests inside this repo. I was focused on testing it from the auth server instead.

Will update the PR, sorry.

**Comment by philbooth** [comment]
@rfk / @dannycoates, I've pushed again with some tests for the device endpoints.

Fwiw, it would be jolly splendid if one of you could merge this in today (assuming you're happy with it), as I'd rather like to open a PR against it tomorrow. :grin:

**Comment by rfk** [comment]
LGTM!

**Pull request merged**
