### PR TITLE
fix(sql): fix sql syntax

### PR DESCRIPTION
**Pull request by vladikoff**
Fixes https://github.com/mozilla/fxa-auth-server/issues/2030

@jrgm r?

### CODE REVIEW

**Comment by vbudhram** [comment]
Looks like it is in multiple spots, https://github.com/mozilla/fxa-auth-db-mysql/search?utf8=%E2%9C%93&q=ALGORITHM+%3D+INPLACE+LOCK+%3D+NONE&type=

**Comment by vladikoff** [comment]
```
ne.
{"Timestamp":1501779391852000000,"Logger":"fxa-auth-db-server","Type":"bin.db_patcher.patch-error","Severity":2,"Pid":4955,"EnvVersion":"2.0","Fields":{"err":"Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ' LOCK = NONE;\n\nALTER TABLE securityEvents\nDROP COLUMN tokenId,\nALGORITHM = INPLA' at line 1"}}
```

**Comment by korosuke114** [comment]
Hi

When I changed syntax. I got another error as follow.

fxa@mx ~/fxa-auth-server $ npm run start-mysql

> fxa-auth-server@1.92.0 start-mysql /home/fxa/fxa-auth-server
> NODE_ENV=dev scripts/start-local-mysql.sh 2>&1

keys file already exists
README.md  index.js  node_modules  package.json  test
mail_helper started...
{"Timestamp":1501819104109000000,"Logger":"fxa-auth-db-server","Type":"bin.db_patcher.patch-error","Severity":2,"Pid":27334,"EnvVersion":"2.0","Fields":{"err":"Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ' LOCK = NONE;\n\nCREATE INDEX securityEvents_uid_ipAddrHmac_createdAt\nON securityE' at line 3"}}

npm ERR! Linux 4.9.34-gentoo
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "start-mysql"
npm ERR! node v4.6.1
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE
npm ERR! fxa-auth-server@1.92.0 start-mysql: `NODE_ENV=dev scripts/start-local-mysql.sh 2>&1`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the fxa-auth-server@1.92.0 start-mysql script 'NODE_ENV=dev scripts/start-local-mysql.sh 2>&1'.
npm ERR! This is most likely a problem with the fxa-auth-server package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     NODE_ENV=dev scripts/start-local-mysql.sh 2>&1
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs fxa-auth-server
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls fxa-auth-server
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/fxa/fxa-auth-server/npm-debug.log
fxa@mx ~/fxa-auth-server $

**Comment by korosuke114** [comment]
Hi

I found one statement from mysql document.

The ALTER TABLE clause LOCK=NONE is not allowed if there are ON...CASCADE or ON...SET NULL constraints on the table.

in patch patch-035-036.sql has following statement.

CREATE INDEX securityEvents_uid_tokenVerificationId
ON securityEvents(uid, tokenVerificationId)
ALGORITHM = INPLACE,LOCK = NONE;

CREATE INDEX securityEvents_uid_ipAddrHmac_createdAt
ON securityEvents(uid, ipAddrHmac, createdAt)
ALGORITHM = INPLACE, LOCK = NONE;

Does "Create index" with "ON" statement support "LOCK = NONE" statement?

I tried to change "LOCK = NONE" to "LOCK = DEFAULT" and "LOCK = SHARE". all of statement reject and syntax error.

however, I removed Algorithm statement. sql command successfuly.

Here is operation ouptut.

MariaDB [ffauth]> CREATE INDEX securityEvents_uid_tokenVerificationId ON securityEvents(uid, tokenVerificationId) ALGORITHM = INPLACE, LOCK = DEFAULT;
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ' LOCK = DEFAULT' at line 1

MariaDB [ffauth]> CREATE INDEX securityEvents_uid_tokenVerificationId ON securityEvents(uid, tokenVerificationId) ALGORITHM = INPLACE, LOCK = SHARE;
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ' LOCK = SHARE' at line 1

MariaDB [ffauth]> CREATE INDEX securityEvents_uid_tokenVerificationId ON securityEvents(uid, tokenVerificationId) ALGORITHM = INPLACE, LOCK = NONE;
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ' LOCK = NONE' at line 1

MariaDB [ffauth]> CREATE INDEX securityEvents_uid_tokenVerificationId ON securityEvents(uid, tokenVerificationId);

**Pull request closed without merging**
